# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b7e9fe92a27a4ab7733b2a87acc23574c2e6ad073e30c73c21f152c7b1202fab7b35977bacb22b12d698c28f91b7d2f894de9e3582426f9d0059592eb65933

test:
  secret_key_base: 5c4f7d42ac6b609b78478433938cc708b626485e339c65b3da5cfbd5ae8ff575d2deaccf02ad07ffa6cc4e064cc3cf053a874adfa9e231662845e06ba07a5b62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
